name: Publish website reactive-graph.io

on:
  push:
    branches: [ main ]
    paths:
      - "src/**/*"
      - "script/**/*"
      - "package.json"
      - ".github/workflows/reactive-graph-io.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**/*"
      - "script/**/*"
      - "package.json"
      - ".github/workflows/reactive-graph-io.yml"

jobs:
  publish:
    name: Publish website reactive-graph.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install
      - run: pnpm run build
      - run: echo "www.reactive-graph.io" > build/CNAME
      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
